### ISSUE TITLE
New Api method request

### ISSUE THREAD

**Issue by PeterSawyer** [KyleGobel/Hipchat-CS#16]
Any chance we can add **View user** so I can obtain extra information on the users?

I want to be able to utilise the **photo_url** for users who fit a category in another system.

https://www.hipchat.com/docs/apiv2/method/view_user

Thanks
Peter

**Comment by BilliamBrown** [comment]
Hello @PeterSawyer 
I have just made a PR, https://github.com/KyleGobel/Hipchat-CS/pull/17 which will add this functionality for you. 

I'm just waiting on @KyleGobel to merge it in.

**Comment by KyleGobel** [comment]
just merged and pushed to nuget :)

**Comment by PeterSawyer** [comment]
Thanks guys, works like a charm :+1:
